services:
  backend:
    build: ./verdikt-backend
    container_name: verdikt-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - verdikt-network

  frontend:
    build: ./verdikt-frontend
    container_name: verdikt-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - verdikt-network

networks:
  verdikt-network:
    driver: bridge
